"""
Reviewer Node -- Applies the Coder's proposed fix and runs it in the sandbox.

This is a deterministic node (no LLM). It validates the code safely
inside the Docker container and returns any test errors.
"""

from __future__ import annotations

from issue_resolver.state import AgentState
from issue_resolver.tools.sandbox_tools import apply_diff_in_sandbox, run_tests_in_sandbox
from issue_resolver.utils.logger import append_to_history


def reviewer_node(state: AgentState) -> dict:
    """
    Applies the patch generated by the Coder inside the sandbox,
    and runs the main application to see if it crashes.
    """
    proposed_fix = state.get("proposed_fix", "")
    repo_path = state.get("repo_path", "")

    if not proposed_fix:
        # Shouldn't happen unless routing is broken, but handle it gracefully
        print("[Reviewer] [WARN] No proposed fix found in state.")
        return {"errors": "No fix proposed.", "history": append_to_history("Reviewer", "Failure", "No fix proposed to review.")}

    try:
        # 1. Apply the diff
        print("[Reviewer] Applying proposed fix in the sandbox...")
        patch_output = apply_diff_in_sandbox(proposed_fix, repo_path)
        
        if "Error" in patch_output:
            # Docker/sandbox not available -- skip validation gracefully
            if "Sandbox container not found" in patch_output:
                print("[Reviewer] Docker sandbox unavailable -- skipping validation.")
                return {
                    "errors": "",
                    "history": append_to_history("Reviewer", "Skipped",
                        "Docker sandbox unavailable. Fix generated but not validated."),
                }
            print("[Reviewer] [FAIL] Patch failed to apply.")
            return {"errors": f"Failed to apply patch:\n{patch_output}", "history": append_to_history("Reviewer", "Apply Patch Failed", patch_output)}

        # 2. Run the main application or auto-generated tests
        print("[Reviewer] Running validation in sandbox...")
        success, output = run_tests_in_sandbox(proposed_fix)

        # 3. Handle the result
        history_additions = append_to_history("Reviewer", "Test Execution", output)
        
        if success:
            print("[Reviewer] [OK] Code ran successfully.")
            return {"errors": "", "history": history_additions}
        else:
            print("[Reviewer] [FAIL] Code execution failed.")
            return {"errors": output, "history": history_additions}

    except Exception as exc:
        error_msg = str(exc)
        print(f"[Reviewer] [ERROR] Exception: {error_msg}")
        # Docker not running is common -- don't crash the graph
        if "docker" in error_msg.lower() or "CreateFile" in error_msg:
            print("[Reviewer] Docker unavailable -- skipping sandbox validation.")
            return {
                "errors": "",
                "history": append_to_history("Reviewer", "Skipped",
                    "Docker unavailable. Fix generated but not validated in sandbox."),
            }
        return {
            "errors": f"Reviewer error: {error_msg}",
            "history": append_to_history("Reviewer", "Error", error_msg),
        }
