"""
Reviewer Node -- Applies the Coder's proposed fix and runs it in the sandbox.

This is a deterministic node (no LLM). It validates the code safely
inside the Docker container and returns any test errors with categorization.
"""

from __future__ import annotations

import re
from langchain_core.messages import HumanMessage

from issue_resolver.state import AgentState
from issue_resolver.config import REVIEWER_MODEL_CANDIDATES
from issue_resolver.llm_utils import invoke_with_role_fallback
from issue_resolver.tools.sandbox_tools import (
    apply_diff_in_sandbox,
    run_tests_in_sandbox,
    format_parsed_error_summary,
)
from issue_resolver.utils.logger import append_to_history


def _categorize_error(error_text: str) -> str:
    """Classify error into: SyntaxError | EnvironmentError | LogicFailure | FrameworkError."""
    lower = error_text.lower()
    
    patterns = {
        "SyntaxError": (r"syntaxerror|unexpected token|invalid syntax|parse error", 2.0),
        "EnvironmentError": (r"modulenotfound|importerror|no such file|not found error|cannot find", 2.0),
        "LogicFailure": (r"assertion|expected.*got|test failed|failure", 1.5),
        "FrameworkError": (r"cannot find|not a function|undefined|typeerror", 1.0),
    }
    
    scores = {}
    for category, (pattern, weight) in patterns.items():
        if re.search(pattern, lower):
            scores[category] = weight
    
    return max(scores, key=scores.get) if scores else "UnknownError"


def _extract_line_numbers(error_text: str) -> str:
    """Extract line numbers from error traceback."""
    lines = []
    
    # Python: "line XX" or "File ..., line XX"
    python_pattern = r'line\s+(\d+)'
    # C#: "CS XXXX (XX,YY)"
    csharp_pattern = r'\((\d+),\d+\)'
    # JavaScript: "at ... (X:Y)"
    js_pattern = r':\s*(\d+):\d+'
    
    for pattern in [python_pattern, csharp_pattern, js_pattern]:
        matches = re.findall(pattern, error_text)
        if matches:
            lines.extend(matches[:5])  # Limit to first 5 line numbers
    
    if lines:
        return "lines " + ", ".join(sorted(set(lines)))
    return ""


def reviewer_node(state: AgentState) -> dict:
    """
    Applies the patch generated by the Coder inside the sandbox,
    and runs the main application to see if it crashes.

    Returns ``validation_status`` as one of:
      - ``"passed"``       – tests/build ran and succeeded
      - ``"failed"``       – tests/build ran and failed (errors populated)
      - ``"inconclusive"`` – validation could not run (Docker missing, etc.)
    
    Test-Driven Validation (Phase 5):
    - If test_code was generated, validator previously confirmed it FAILS before fix.
    - After the fix is applied: runs tests and confirms they now PASS.
    - This ensures the fix is verified against a concrete reproduction case.
    """
    proposed_fix = state.get("proposed_fix", "")
    repo_path = state.get("repo_path", "")
    test_code = state.get("test_code", "")
    test_file_path = state.get("test_file_path", "")

    if not proposed_fix:
        print("[Reviewer] [WARN] No proposed fix found in state.")
        return {
            "errors": "No fix proposed.",
            "validation_status": "failed",
            "history": append_to_history("Reviewer", "Failure", "No fix proposed to review."),
        }

    try:
        # 1. Apply the diff
        print("[Reviewer] Applying proposed fix in the sandbox...")
        patch_output = apply_diff_in_sandbox(proposed_fix, repo_path)
        
        # Test-Driven Validation (Phase 5):
        # The test was already verified to FAIL before the fix (by TestValidator).
        # Now we apply the fix and run tests to confirm they PASS.
        if test_code and test_file_path:
            print(f"[Reviewer] [TEST-DRIVEN] Test file '{test_file_path}' will be validated after fix is applied.")
            print("[Reviewer] [TEST-DRIVEN] If the test now passes, the fix resolves the issue.")

        if "Error" in patch_output:
            if "Sandbox container not found" in patch_output:
                print("[Reviewer] Docker sandbox unavailable -- validation inconclusive.")
                return {
                    "errors": "",
                    "validation_status": "inconclusive",
                    "history": append_to_history("Reviewer", "Skipped",
                        "Docker sandbox unavailable. Fix generated but not validated."),
                }
            print("[Reviewer] [FAIL] Patch failed to apply.")
            return {
                "errors": f"Failed to apply patch:\n{patch_output}",
                "validation_status": "failed",
                "history": append_to_history("Reviewer", "Apply Patch Failed", patch_output),
            }

        # 2. Run build/test strategy in sandbox
        print("[Reviewer] Running validation in sandbox...")
        success, output = run_tests_in_sandbox(proposed_fix)

        environment_type = str(state.get("environment_config", {}).get("environment_type", "python")).lower()
        parsed_summary = format_parsed_error_summary(environment_type, output)

        # Optional fast summarizer model. If unavailable, keep parser-only summary.
        condensed = parsed_summary
        if not success:
            prompt = (
                "Summarize this build/test failure for a coding agent in one line. "
                "Include the most actionable file/line/error token.\n\n"
                f"Environment: {environment_type}\n"
                f"Parsed: {parsed_summary}\n"
                f"Raw:\n{output[:3000]}"
            )
            try:
                resp, _ = invoke_with_role_fallback(
                    role="Reviewer",
                    candidates=REVIEWER_MODEL_CANDIDATES,
                    messages=[HumanMessage(content=prompt)],
                    temperature=0,
                    max_tokens=180,
                )
                llm_summary = (getattr(resp, "content", "") or "").strip()
                if llm_summary:
                    condensed = llm_summary
            except Exception as exc:
                print(f"[Reviewer] [WARN] Reviewer summarizer unavailable: {exc}")

        history_payload = f"{condensed}\n\n[RAW]\n{output[:5000]}"
        history_additions = append_to_history("Reviewer", "Test Execution", history_payload)

        if success:
            print("[Reviewer] [OK] Code ran successfully.")
            return {
                "errors": "",
                "validation_status": "passed",
                "history": history_additions
            }

        print("[Reviewer] [FAIL] Code execution failed.")
        
        # Categorize error for Coder's debugging mode
        error_category = _categorize_error(output)
        error_line_numbers = _extract_line_numbers(output)
        
        print(f"[Reviewer] Error category: {error_category}, Lines: {error_line_numbers}")
        
        return {
            "errors": condensed,
            "validation_status": "failed",
            "error_category": error_category,
            "test_error_context": output[:500],  # First 500 chars of error
            "error_line_numbers": error_line_numbers,
            "history": history_additions,
        }

    except Exception as exc:
        error_msg = str(exc)
        print(f"[Reviewer] [ERROR] Exception: {error_msg}")
        if "docker" in error_msg.lower() or "CreateFile" in error_msg:
            print("[Reviewer] Docker unavailable -- validation inconclusive.")
            return {
                "errors": "",
                "validation_status": "inconclusive",
                "history": append_to_history("Reviewer", "Skipped",
                    "Docker unavailable. Fix generated but not validated in sandbox."),
            }
        return {
            "errors": f"Reviewer error: {error_msg}",
            "validation_status": "failed",
            "history": append_to_history("Reviewer", "Error", error_msg),
        }
