"""
Test Validator Node -- Runs the generated test to verify it fails before fix.

This node executes the test generated by TestGen to confirm it reproduces
the issue. The failure output is captured and passed to the Coder as a
concrete reproduction case.

By forcing test execution BEFORE coding, we ensure:
1. The issue is reproducible (not a phantom bug)
2. The Coder gets a concrete stack trace to work with
3. We can verify the fix makes the test pass
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

from issue_resolver.state import AgentState
from issue_resolver.utils.logger import append_to_history
from issue_resolver.tools.sandbox_tools import apply_diff_in_sandbox, run_tests_in_sandbox


def test_validator_node(state: AgentState) -> dict:
    """Run the generated test to verify it fails and capture the output."""
    print("[TestValidator] Running generated test to reproduce issue...")

    test_code = state.get("test_code", "")
    test_file_path = state.get("test_file_path", "")
    test_framework_used = state.get("test_framework_used", "pytest")
    repo_path = state.get("repo_path", ".")
    iterations = state.get("iterations", 0)
    
    if not test_code:
        print("[TestValidator] [SKIP] No test code generated yet")
        return {
            "test_runs_initially": False,
            "errors": "",
            "history": append_to_history("TestValidator", "Skipped", "No test code to validate"),
        }
    
    print(f"[TestValidator] Test framework: {test_framework_used}")
    print(f"[TestValidator] Test file: {test_file_path}")
    
    # Normalize test file path
    test_file_normalized = test_file_path
    if test_file_normalized.startswith("./"):
        test_file_normalized = test_file_normalized[2:]
    
    try:
        # Write test file to sandbox
        full_test_path = Path(repo_path) / test_file_normalized
        full_test_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(full_test_path, "w", encoding="utf-8") as f:
            f.write(test_code)
        print(f"[TestValidator] ✅ Test file written to {full_test_path}")
        
    except Exception as exc:
        error_msg = f"Failed to write test file: {exc}"
        print(f"[TestValidator] [ERROR] {error_msg}")
        return {
            "test_runs_initially": False,
            "errors": error_msg,
            "iterations": iterations + 1,
            "history": append_to_history("TestValidator", "Write Failed", error_msg),
        }
    
    # Run test to get reproduction output
    print("[TestValidator] Running test (expecting failure to reproduce bug)...")
    try:
        # For now, use a simple approach: try to run the test locally if possible
        # Otherwise, we'll validate in the sandbox during review
        test_output = _run_test_locally(
            test_file_normalized,
            repo_path,
            test_framework_used
        )
        
        if test_output.startswith("[SANDBOX_REQUIRED]"):
            # Sandbox is required for execution
            print("[TestValidator] Sandbox execution required. Test will validate during review.")
            return {
                "test_runs_initially": False,  # Will validate after fix attempt
                "errors": "",
                "iterations": iterations + 1,
                "history": append_to_history(
                    "TestValidator",
                    "Deferred",
                    "Test file created. Validation will occur in sandbox during review."
                ),
            }
        
        # Test ran successfully (locally)
        if "FAILED" in test_output or "ERROR" in test_output or "failed" in test_output.lower():
            print("[TestValidator] ✅ Test fails as expected (issue reproduced)")
            return {
                "test_runs_initially": False,  # Test failed (as expected - bug exists)
                "errors": test_output[:2000],  # Capture output for Coder context
                "iterations": iterations + 1,
                "history": append_to_history(
                    "TestValidator",
                    "Reproduction Confirmed",
                    f"Test fails as expected:\n{test_output[:500]}"
                ),
            }
        else:
            # Test passed when it shouldn't
            print("[TestValidator] [WARN] Test passed unexpectedly. Issue may not be reproducible.")
            return {
                "test_runs_initially": True,  # Test passed (unexpected - bug might not exist)
                "errors": "Test passed unexpectedly. Issue may not be reproducible with this test.",
                "iterations": iterations + 1,
                "history": append_to_history(
                    "TestValidator",
                    "Warning",
                    "Test passed when expected to fail. Issue may not be reproducible."
                ),
            }
    
    except Exception as exc:
        # Local execution failed, defer to sandbox
        error_msg = f"Local test execution failed: {exc}"
        print(f"[TestValidator] [WARN] {error_msg}. Will defer to sandbox validation.")
        return {
            "test_runs_initially": False,
            "errors": "",
            "iterations": iterations + 1,
            "history": append_to_history("TestValidator", "Deferred", error_msg),
        }


def _run_test_locally(test_file: str, repo_path: str, framework: str) -> str:
    """Attempt to run test locally. Returns output or '[SANDBOX_REQUIRED]'."""
    
    # Determine test command based on framework
    commands = {
        "pytest": ["python", "-m", "pytest", test_file, "-v"],
        "unittest": ["python", "-m", "unittest", test_file],
        "jest": ["npx", "jest", test_file],
        "xunit": ["dotnet", "test", test_file],
        "nunit": ["dotnet", "test", test_file],
        "vitest": ["npx", "vitest", test_file],
    }
    
    cmd = commands.get(framework.lower(), ["python", "-m", "pytest", test_file, "-v"])
    
    try:
        result = subprocess.run(
            cmd,
            cwd=repo_path,
            capture_output=True,
            text=True,
            timeout=30,
            check=False,  # Don't raise on non-zero exit
        )
        return result.stdout + result.stderr
    except subprocess.TimeoutExpired:
        return "[SANDBOX_REQUIRED]"
    except FileNotFoundError:
        # Test framework not installed locally
        return "[SANDBOX_REQUIRED]"
    except Exception as e:
        return "[SANDBOX_REQUIRED]"
