"""
Sandbox tools -- Uses the Docker SDK to interact with the sandbox container.
"""

import os
import re
from typing import Any

from issue_resolver.runtime_context import get_environment_config

try:
    import docker
except ImportError:
    docker = None


def _check_docker_available():
    """Check if docker module is available; raise helpful error if not."""
    if docker is None:
        raise ImportError(
            "Docker module not installed. Install it with: pip install docker\n"
            "The sandbox tools require Docker to be installed and running."
        )


# ---------------------------------------------------------------------------
# Diff repair: fix truncated hunk headers generated by the LLM
# ---------------------------------------------------------------------------
def _repair_diff_hunks(diff_text: str) -> str:
    """
    Re-count the old/new line counts in every @@ hunk header so they match
    the actual body lines.  This fixes the "unexpected end of file in patch"
    error that happens when the LLM declares more context lines than it
    actually outputs.
    """
    hunk_re = re.compile(
        r"^@@ -(\d+)(?:,\d+)? \+(\d+)(?:,\d+)?(?: @@.*)$"
    )
    lines = diff_text.split("\n")
    result: list[str] = []
    hunk_header_idx: int | None = None     # index in `result` of current header
    old_start = new_start = 0
    old_count = new_count = 0

    def _flush_hunk():
        """Rewrite the stored hunk header with correct counts."""
        nonlocal hunk_header_idx, old_count, new_count
        if hunk_header_idx is None:
            return
        m = hunk_re.match(result[hunk_header_idx])
        if m:
            # Preserve any trailing @@ function context
            trailer = result[hunk_header_idx].split("@@", 2)
            func_ctx = trailer[2] if len(trailer) > 2 else ""
            result[hunk_header_idx] = (
                f"@@ -{old_start},{old_count} +{new_start},{new_count} @@{func_ctx}"
            )
        hunk_header_idx = None

    for line in lines:
        m = hunk_re.match(line)
        if m:
            _flush_hunk()                       # close previous hunk
            old_start = int(m.group(1))
            new_start = int(m.group(2))
            old_count = 0
            new_count = 0
            hunk_header_idx = len(result)
            result.append(line)                  # placeholder, rewritten later
        elif hunk_header_idx is not None:
            # Inside a hunk body
            if line.startswith("-"):
                old_count += 1
                result.append(line)
            elif line.startswith("+"):
                new_count += 1
                result.append(line)
            elif line.startswith(" ") or line == "":
                # context line (or blank context)
                old_count += 1
                new_count += 1
                result.append(line)
            else:
                # Unrecognised line (e.g. next file header) -- end the hunk
                _flush_hunk()
                result.append(line)
        else:
            result.append(line)

    _flush_hunk()                               # close final hunk
    return "\n".join(result)

def get_sandbox_container():
    """Finds the sandbox container using labels."""
    _check_docker_available()
    try:
        client = docker.from_env()
        containers = client.containers.list(filters={"label": "com.issue_resolver.role=sandbox"})
        if not containers:
            return None
        return containers[0]
    except Exception as e:
        print(f"[Sandbox] Cannot connect to Docker: {e}")
        return None

def apply_diff_in_sandbox(diff: str, repo_path: str) -> str:
    """
    Applies a code diff (patch) inside the Docker sandbox.
    Uses bash -c for shell redirection and git for clean state management.
    """
    sandbox = get_sandbox_container()
    if not sandbox:
        return "Error: Sandbox container not found. Is it running?"
        
    # 1. Idempotency: Initialize git and check for existing baseline
    sandbox.exec_run("git init", workdir="/workspace")
    sandbox.exec_run(
        'bash -c "git config user.email \'agent@local\' && git config user.name \'Agent\'"',
        workdir="/workspace"
    )
    
    # Check if we already have a baseline tag from a previous iteration
    tag_check = sandbox.exec_run("git tag -l baseline", workdir="/workspace")
    has_baseline = tag_check.output.decode("utf-8", errors="ignore").strip() == "baseline"
    
    if has_baseline:
        # Subsequent iteration: hard-reset to the ORIGINAL un-patched code
        print("[Sandbox] Resetting to original baseline...")
        sandbox.exec_run("git reset --hard baseline", workdir="/workspace")
        sandbox.exec_run("git clean -fd", workdir="/workspace")
    else:
        # First iteration: normalize line endings, commit, and TAG the baseline
        print("[Sandbox] Creating initial baseline...")
        sandbox.exec_run(
            "bash -c \"find . -type f -not -path '*/.*' -exec sed -i 's/\\r$//' {} +\"",
            workdir="/workspace"
        )
        sandbox.exec_run("git add .", workdir="/workspace")
        sandbox.exec_run('bash -c "git commit -m \'baseline\' || true"', workdir="/workspace")
        # Tag it so we can always return to the ORIGINAL state
        sandbox.exec_run("git tag baseline", workdir="/workspace")
    
    # 2. Prepare the diff string: normalize line endings and clean up
    diff = diff.replace("\r\n", "\n").strip()
    # Clean up hallucinated prefixes
    diff = diff.replace("sandbox_workspace/", "")
    # Strip any leading garbage (like the bare word 'diff') before the real header
    if diff.startswith("diff\n"):
        diff = diff[5:].strip()
        
    # Clean up hallucinated line numbers like ` 14: ` or `+17: ` or `- 20:`
    cleaned_lines = []
    for line in diff.split("\n"):
        if line.startswith("---") or line.startswith("+++"):
            cleaned_lines.append(line)
        else:
            m = re.match(r"^([\+\-\s])(?: *)?\d+:(?: *)(.*)$", line)
            if m:
                cleaned_lines.append(f"{m.group(1)}{m.group(2)}")
            else:
                cleaned_lines.append(line)
    diff = "\n".join(cleaned_lines)
    
    if "---" not in diff or "+++" not in diff:
        return "Error: The unified diff is missing the `--- a/file` and `+++ b/file` file headers."

    if not diff:
        return "Error: Empty diff provided."
    
    # Repair truncated hunk headers so `patch` doesn't hit unexpected EOF
    diff = _repair_diff_hunks(diff)
    
    # --- No-op diff detector ---
    # Check if the diff actually changes any code lines (not just whitespace/docstrings)
    has_real_change = False
    for line in diff.split("\n"):
        if line.startswith("-") and not line.startswith("---"):
            stripped = line[1:].strip()
            if stripped and not stripped.startswith("#") and stripped not in ('"""', "'''"):
                has_real_change = True
                break
        if line.startswith("+") and not line.startswith("+++"):
            stripped = line[1:].strip()
            if stripped and not stripped.startswith("#") and stripped not in ('"""', "'''"):
                has_real_change = True
                break
    
    if not has_real_change:
        return "Error: The proposed diff is a NO-OP (only changes whitespace/comments/docstrings). You must change actual code logic."

    # 3. Write the patch file locally (mapped to the container via volume)
    patch_path = os.path.join(repo_path, "fix.patch")
    os.makedirs(os.path.dirname(patch_path), exist_ok=True)
    
    try:
        if not diff.endswith("\n"):
            diff += "\n"
            
        with open(patch_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(diff)
    except Exception as e:
        return f"Error writing patch file locally: {e}"
    
    # Debug: print first few lines of the patch
    print(f"[Sandbox] Patch content (first 300 chars):\n{diff[:300]}")
        
    # 4. Apply the patch inside the container
    print("[Sandbox] Applying patch...")
    patch_result = sandbox.exec_run(
        ["bash", "-c", "patch -l --fuzz=3 -p1 < fix.patch"], 
        workdir="/workspace"
    )
    
    output = patch_result.output.decode('utf-8', errors='ignore')
    print(f"[Sandbox] Patch result (exit={patch_result.exit_code}): {output}")
    
    if patch_result.exit_code != 0:
         return f"Error applying patch:\n{output}"
         
    return f"Patch applied successfully.\n{output}"

def _extract_modified_files_from_diff(diff: str) -> list[str]:
    """Extract the file paths that the diff modifies from +++ headers."""
    import re
    files = []
    for line in diff.split("\n"):
        # Match +++ b/src/utils.py or +++ b/path/to/file.py
        m = re.match(r"^\+\+\+ [ab]/(.+)$", line)
        if m:
            files.append(m.group(1))
    return files


def parse_dotnet_error_trace(output: str) -> dict[str, Any]:
    """Extract .NET compiler diagnostics including CS code and location."""
    findings: list[dict[str, Any]] = []
    pattern = re.compile(
        r"^(?P<file>.+?)\((?P<line>\d+),(?P<column>\d+)\):\s*error\s*(?P<code>CS\d+)\s*:\s*(?P<msg>.+)$",
        re.IGNORECASE,
    )
    for raw_line in output.splitlines():
        line = raw_line.strip()
        match = pattern.match(line)
        if not match:
            continue
        findings.append(
            {
                "file": match.group("file"),
                "line": int(match.group("line")),
                "column": int(match.group("column")),
                "code": match.group("code").upper(),
                "message": match.group("msg").strip(),
            }
        )

    return {
        "type": "dotnet",
        "count": len(findings),
        "primary": findings[0] if findings else None,
        "findings": findings[:10],
    }


def parse_node_error_trace(output: str) -> dict[str, Any]:
    """Extract NodeJS stack trace focus and likely culprit file."""
    stack_lines = [
        line.strip()
        for line in output.splitlines()
        if line.strip().startswith("at ") or ".js:" in line or ".ts:" in line
    ]
    culprit = None
    pattern = re.compile(r"(?P<file>[A-Za-z0-9_./\\-]+\.(?:js|ts|tsx|jsx)):(?P<line>\d+)(?::(?P<col>\d+))?")
    for line in stack_lines:
        match = pattern.search(line)
        if match:
            culprit = {
                "file": match.group("file"),
                "line": int(match.group("line")),
                "column": int(match.group("col")) if match.group("col") else None,
            }
            break

    lower = output.lower()
    signature = "hang" if any(tok in lower for tok in ("timeout", "hang", "hung", "did not exit")) else "error"
    return {
        "type": "nodejs",
        "signature": signature,
        "culprit": culprit,
        "stack": stack_lines[:12],
    }


def parse_eslint_error_trace(output: str) -> dict[str, Any]:
    """Extract eslint file and line diagnostics from lint output."""
    findings: list[dict[str, Any]] = []
    pattern = re.compile(
        r"^(?P<file>[^\s].+?\.(?:js|jsx|ts|tsx)):(?P<line>\d+):(?P<column>\d+):\s*(?P<message>.+?)\s{2,}(?P<rule>[\w@\-/]+)$"
    )
    for raw_line in output.splitlines():
        line = raw_line.strip()
        match = pattern.match(line)
        if not match:
            continue
        findings.append(
            {
                "file": match.group("file"),
                "line": int(match.group("line")),
                "column": int(match.group("column")),
                "message": match.group("message"),
                "rule": match.group("rule"),
            }
        )
    return {
        "type": "eslint",
        "count": len(findings),
        "primary": findings[0] if findings else None,
        "findings": findings[:10],
    }


def parse_python_error_trace(output: str) -> dict[str, Any]:
    """Extract concise Python failure signal for faster self-repair loops."""
    failed_tests = [line.strip() for line in output.splitlines() if line.strip().startswith("FAILED ")]
    assertions = [line.strip() for line in output.splitlines() if "AssertionError" in line or line.strip().startswith("E   ")]
    return {
        "type": "python",
        "failed_tests": failed_tests[:8],
        "assertions": assertions[:8],
    }


def format_parsed_error_summary(environment_type: str, output: str) -> str:
    """Return concise, coder-actionable summary from raw test/build output."""
    if environment_type == "dotnet":
        parsed = parse_dotnet_error_trace(output)
        primary = parsed.get("primary")
        if primary:
            return (
                f"Dotnet compile error: {primary['code']} at "
                f"{primary['file']}:{primary['line']}:{primary['column']} - {primary['message']}"
            )
        return "Dotnet validation failed without parseable CSxxxx compiler diagnostics."

    if environment_type == "nodejs":
        eslint = parse_eslint_error_trace(output)
        primary_lint = eslint.get("primary")
        if primary_lint:
            return (
                f"ESLint error at {primary_lint['file']}:{primary_lint['line']}:{primary_lint['column']} "
                f"({primary_lint['rule']}): {primary_lint['message']}"
            )

        parsed = parse_node_error_trace(output)
        culprit = parsed.get("culprit")
        if culprit:
            return f"Node {parsed['signature']} trace focuses on {culprit['file']}:{culprit['line']}"
        return f"Node {parsed['signature']} detected without parseable culprit file."

    parsed = parse_python_error_trace(output)
    if parsed["failed_tests"]:
        return f"Python test failures: {', '.join(parsed['failed_tests'][:3])}"
    if parsed["assertions"]:
        return f"Python assertion highlight: {parsed['assertions'][0]}"
    return "Python validation failed with no parseable traceback markers."


def _run_dotnet_strategy(sandbox) -> tuple[bool, str]:
    env_config = get_environment_config()
    framework = str(env_config.get("test_framework", "unknown")).lower()

    test_find = sandbox.exec_run(
        ["bash", "-c", "find . -name '*[Tt]est*.csproj' ! -path '*ApiTests*' | head -1"],
        workdir="/workspace",
    )
    test_proj = test_find.output.decode("utf-8", errors="ignore").strip()

    if not test_proj:
        find_res = sandbox.exec_run(
            ["bash", "-c", "find . -name '*.csproj' ! -path '*[Tt]est*' ! -path '*[Dd]emo*' ! -path '*[Cc]onsole*' | head -1"],
            workdir="/workspace",
        )
        lib_proj = find_res.output.decode("utf-8", errors="ignore").strip()
        if not lib_proj:
            return False, "Error: No test or library projects found for dotnet strategy."
        build_res = sandbox.exec_run(["dotnet", "build", lib_proj], workdir="/workspace")
        return (build_res.exit_code == 0), build_res.output.decode("utf-8", errors="ignore")

    build_res = sandbox.exec_run(["dotnet", "build", test_proj], workdir="/workspace")
    build_out = build_res.output.decode("utf-8", errors="ignore")
    if build_res.exit_code != 0:
        if "NU1301" in build_out or "Unable to load the service index" in build_out:
            return True, "Dotnet restore unavailable in sandbox; build skipped as offline."
        return False, build_out

    test_cmd = ["dotnet", "test", test_proj, "--no-restore", "--no-build", "-v", "minimal"]
    failing_test = str(env_config.get("failing_test_name", "")).strip()
    if failing_test and framework == "xunit":
        test_cmd.extend(["--filter", f"FullyQualifiedName~{failing_test}"])
    elif failing_test and framework == "nunit":
        test_cmd.extend(["--filter", f"Name~{failing_test}"])
    elif failing_test and framework == "mstest":
        test_cmd.extend(["--filter", f"Name~{failing_test}"])

    test_res = sandbox.exec_run(test_cmd, workdir="/workspace")
    test_out = test_res.output.decode("utf-8", errors="ignore")
    if test_res.exit_code == 0:
        return True, test_out
    if "NU1301" in test_out or "Unable to load the service index" in test_out:
        return True, "Build succeeded. Tests skipped (offline mode, NuGet unavailable)."
    return False, test_out


def _run_node_strategy(sandbox) -> tuple[bool, str]:
    install_res = sandbox.exec_run(["npm", "install", "--ignore-scripts"], workdir="/workspace")
    if install_res.exit_code != 0:
        return False, install_res.output.decode("utf-8", errors="ignore")

    lint_res = sandbox.exec_run(["bash", "-c", "npm run lint -- --format unix || true"], workdir="/workspace")
    lint_out = lint_res.output.decode("utf-8", errors="ignore")

    test_res = sandbox.exec_run(["npm", "test"], workdir="/workspace")
    test_out = test_res.output.decode("utf-8", errors="ignore")
    if test_res.exit_code == 0:
        return True, (lint_out + "\n" + test_out).strip()

    if "no test specified" in test_out.lower():
        for entry in ["index.js", "main.js", "app.js", "src/index.js", "src/main.js"]:
            chk = sandbox.exec_run(["test", "-f", entry], workdir="/workspace")
            if chk.exit_code == 0:
                res = sandbox.exec_run(["node", entry], workdir="/workspace")
                out = res.output.decode("utf-8", errors="ignore")
                return (res.exit_code == 0), (lint_out + "\n" + out).strip()
        return True, "No tests configured; Node fallback run skipped."

    return False, (lint_out + "\n" + test_out).strip()


def _run_python_strategy(sandbox, diff: str) -> tuple[bool, str]:
    env = {"PYTHONPATH": "."}

    find_result = sandbox.exec_run(
        ["bash", "-c", "find . -name 'test_*.py' -o -name '*_test.py' | head -5"],
        workdir="/workspace",
    )
    test_files = find_result.output.decode("utf-8", errors="ignore").strip().splitlines()
    test_files = [f.strip() for f in test_files if f.strip()]

    if test_files:
        test_file = test_files[0]
        has_pytest = sandbox.exec_run(["pytest", "--version"]).exit_code == 0
        cmd = ["pytest", test_file] if has_pytest else ["python", test_file]
        result = sandbox.exec_run(cmd, workdir="/workspace", environment=env)
        return (result.exit_code == 0), result.output.decode("utf-8", errors="ignore")

    for entry in ["main.py", "src/main.py", "app.py"]:
        check = sandbox.exec_run(["test", "-f", entry], workdir="/workspace")
        if check.exit_code == 0:
            result = sandbox.exec_run(["python", entry], workdir="/workspace", environment=env)
            return (result.exit_code == 0), result.output.decode("utf-8", errors="ignore")

    modified_files = _extract_modified_files_from_diff(diff)
    if not modified_files:
        return False, "Error: Could not determine which file was modified from the diff."

    script_lines = ["import importlib, sys", "sys.path.insert(0, '.')"]
    for fpath in modified_files:
        if fpath.endswith(".py"):
            mod = fpath[:-3].replace("/", ".").replace("\\", ".")
            script_lines.append(f"try:\n    importlib.import_module('{mod}')\n    print(f'Successfully imported: {mod}')\nexcept Exception as ex:\n    print(f'Failed to import {mod}: {{ex}}')\n    sys.exit(1)")
    script_lines.append("print('All import smoke-tests passed.')")
    test_script = "\n".join(script_lines)

    sandbox.exec_run(["bash", "-c", f"cat > /tmp/_smoke_test.py << 'ENDOFSCRIPT'\n{test_script}\nENDOFSCRIPT"], workdir="/workspace")
    result = sandbox.exec_run(["python", "/tmp/_smoke_test.py"], workdir="/workspace", environment=env)
    return (result.exit_code == 0), result.output.decode("utf-8", errors="ignore")


def run_tests_in_sandbox(diff: str) -> tuple[bool, str]:
    """Validate patch in sandbox using environment-specific strategy commands."""
    sandbox = get_sandbox_container()
    if not sandbox:
        return False, "Error: Sandbox container not found."

    env_config = get_environment_config()
    environment_type = str(env_config.get("environment_type", "unknown")).lower()

    if environment_type not in {"dotnet", "nodejs", "python"}:
        check_csproj = sandbox.exec_run(["bash", "-c", "find . -name '*.csproj' | head -1"], workdir="/workspace")
        check_pkg = sandbox.exec_run(["test", "-f", "package.json"], workdir="/workspace")
        if check_csproj.output.strip():
            environment_type = "dotnet"
        elif check_pkg.exit_code == 0:
            environment_type = "nodejs"
        else:
            environment_type = "python"

    strategy_map = {
        "dotnet": lambda: _run_dotnet_strategy(sandbox),
        "nodejs": lambda: _run_node_strategy(sandbox),
        "python": lambda: _run_python_strategy(sandbox, diff),
    }

    print(f"[Sandbox] Using strategy: {environment_type}")
    success, output = strategy_map[environment_type]()

    if len(output) > 10000:
        summary = format_parsed_error_summary(environment_type, output)
        output = f"{summary}\n\n[TRUNCATED OUTPUT]\n{output[:4500]}\n...\n{output[-1200:]}"

    return success, output

def clean_sandbox():
    """
    Resets the sandbox container to the original baseline state.
    This removes any applied patches and untracked files.
    """
    sandbox = get_sandbox_container()
    if not sandbox:
        print("[Sandbox] Cleanup skipped: Container not found.")
        return
        
    print("[Sandbox] Cleaning sandbox container...")
    # Reset to baseline if it exists
    tag_check = sandbox.exec_run("git tag -l baseline", workdir="/workspace")
    if tag_check.output.decode("utf-8", errors="ignore").strip() == "baseline":
        sandbox.exec_run("git reset --hard baseline", workdir="/workspace")
        sandbox.exec_run("git clean -fd", workdir="/workspace")
    else:
        # If no baseline, just try a generic reset/clean if it's a git repo
        sandbox.exec_run("git reset --hard", workdir="/workspace")
        sandbox.exec_run("git clean -fd", workdir="/workspace")
    print("[Sandbox] Cleanup complete.")
