"""
Sandbox tools -- Uses the Docker SDK to interact with the sandbox container.
"""

import os
import re

try:
    import docker
except ImportError:
    docker = None


def _check_docker_available():
    """Check if docker module is available; raise helpful error if not."""
    if docker is None:
        raise ImportError(
            "Docker module not installed. Install it with: pip install docker\n"
            "The sandbox tools require Docker to be installed and running."
        )


# ---------------------------------------------------------------------------
# Diff repair: fix truncated hunk headers generated by the LLM
# ---------------------------------------------------------------------------
def _repair_diff_hunks(diff_text: str) -> str:
    """
    Re-count the old/new line counts in every @@ hunk header so they match
    the actual body lines.  This fixes the "unexpected end of file in patch"
    error that happens when the LLM declares more context lines than it
    actually outputs.
    """
    hunk_re = re.compile(
        r"^@@ -(\d+)(?:,\d+)? \+(\d+)(?:,\d+)?(?: @@.*)$"
    )
    lines = diff_text.split("\n")
    result: list[str] = []
    hunk_header_idx: int | None = None     # index in `result` of current header
    old_start = new_start = 0
    old_count = new_count = 0

    def _flush_hunk():
        """Rewrite the stored hunk header with correct counts."""
        nonlocal hunk_header_idx, old_count, new_count
        if hunk_header_idx is None:
            return
        m = hunk_re.match(result[hunk_header_idx])
        if m:
            # Preserve any trailing @@ function context
            trailer = result[hunk_header_idx].split("@@", 2)
            func_ctx = trailer[2] if len(trailer) > 2 else ""
            result[hunk_header_idx] = (
                f"@@ -{old_start},{old_count} +{new_start},{new_count} @@{func_ctx}"
            )
        hunk_header_idx = None

    for line in lines:
        m = hunk_re.match(line)
        if m:
            _flush_hunk()                       # close previous hunk
            old_start = int(m.group(1))
            new_start = int(m.group(2))
            old_count = 0
            new_count = 0
            hunk_header_idx = len(result)
            result.append(line)                  # placeholder, rewritten later
        elif hunk_header_idx is not None:
            # Inside a hunk body
            if line.startswith("-"):
                old_count += 1
                result.append(line)
            elif line.startswith("+"):
                new_count += 1
                result.append(line)
            elif line.startswith(" ") or line == "":
                # context line (or blank context)
                old_count += 1
                new_count += 1
                result.append(line)
            else:
                # Unrecognised line (e.g. next file header) -- end the hunk
                _flush_hunk()
                result.append(line)
        else:
            result.append(line)

    _flush_hunk()                               # close final hunk
    return "\n".join(result)

def get_sandbox_container():
    """Finds the sandbox container using labels."""
    _check_docker_available()
    try:
        client = docker.from_env()
        containers = client.containers.list(filters={"label": "com.issue_resolver.role=sandbox"})
        if not containers:
            return None
        return containers[0]
    except Exception as e:
        print(f"[Sandbox] Cannot connect to Docker: {e}")
        return None

def apply_diff_in_sandbox(diff: str, repo_path: str) -> str:
    """
    Applies a code diff (patch) inside the Docker sandbox.
    Uses bash -c for shell redirection and git for clean state management.
    """
    sandbox = get_sandbox_container()
    if not sandbox:
        return "Error: Sandbox container not found. Is it running?"
        
    # 1. Idempotency: Initialize git and check for existing baseline
    sandbox.exec_run("git init", workdir="/workspace")
    sandbox.exec_run(
        'bash -c "git config user.email \'agent@local\' && git config user.name \'Agent\'"',
        workdir="/workspace"
    )
    
    # Check if we already have a baseline tag from a previous iteration
    tag_check = sandbox.exec_run("git tag -l baseline", workdir="/workspace")
    has_baseline = tag_check.output.decode("utf-8", errors="ignore").strip() == "baseline"
    
    if has_baseline:
        # Subsequent iteration: hard-reset to the ORIGINAL un-patched code
        print("[Sandbox] Resetting to original baseline...")
        sandbox.exec_run("git reset --hard baseline", workdir="/workspace")
        sandbox.exec_run("git clean -fd", workdir="/workspace")
    else:
        # First iteration: normalize line endings, commit, and TAG the baseline
        print("[Sandbox] Creating initial baseline...")
        sandbox.exec_run(
            "bash -c \"find . -type f -not -path '*/.*' -exec sed -i 's/\\r$//' {} +\"",
            workdir="/workspace"
        )
        sandbox.exec_run("git add .", workdir="/workspace")
        sandbox.exec_run('bash -c "git commit -m \'baseline\' || true"', workdir="/workspace")
        # Tag it so we can always return to the ORIGINAL state
        sandbox.exec_run("git tag baseline", workdir="/workspace")
    
    # 2. Prepare the diff string: normalize line endings and clean up
    diff = diff.replace("\r\n", "\n").strip()
    # Clean up hallucinated prefixes
    diff = diff.replace("sandbox_workspace/", "")
    # Strip any leading garbage (like the bare word 'diff') before the real header
    if diff.startswith("diff\n"):
        diff = diff[5:].strip()
        
    # Clean up hallucinated line numbers like ` 14: ` or `+17: ` or `- 20:`
    cleaned_lines = []
    for line in diff.split("\n"):
        if line.startswith("---") or line.startswith("+++"):
            cleaned_lines.append(line)
        else:
            m = re.match(r"^([\+\-\s])(?: *)?\d+:(?: *)(.*)$", line)
            if m:
                cleaned_lines.append(f"{m.group(1)}{m.group(2)}")
            else:
                cleaned_lines.append(line)
    diff = "\n".join(cleaned_lines)
    
    if "---" not in diff or "+++" not in diff:
        return "Error: The unified diff is missing the `--- a/file` and `+++ b/file` file headers."

    if not diff:
        return "Error: Empty diff provided."
    
    # Repair truncated hunk headers so `patch` doesn't hit unexpected EOF
    diff = _repair_diff_hunks(diff)
    
    # --- No-op diff detector ---
    # Check if the diff actually changes any code lines (not just whitespace/docstrings)
    has_real_change = False
    for line in diff.split("\n"):
        if line.startswith("-") and not line.startswith("---"):
            stripped = line[1:].strip()
            if stripped and not stripped.startswith("#") and stripped not in ('"""', "'''"):
                has_real_change = True
                break
        if line.startswith("+") and not line.startswith("+++"):
            stripped = line[1:].strip()
            if stripped and not stripped.startswith("#") and stripped not in ('"""', "'''"):
                has_real_change = True
                break
    
    if not has_real_change:
        return "Error: The proposed diff is a NO-OP (only changes whitespace/comments/docstrings). You must change actual code logic."

    # 3. Write the patch file locally (mapped to the container via volume)
    patch_path = os.path.join(repo_path, "fix.patch")
    os.makedirs(os.path.dirname(patch_path), exist_ok=True)
    
    try:
        if not diff.endswith("\n"):
            diff += "\n"
            
        with open(patch_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(diff)
    except Exception as e:
        return f"Error writing patch file locally: {e}"
    
    # Debug: print first few lines of the patch
    print(f"[Sandbox] Patch content (first 300 chars):\n{diff[:300]}")
        
    # 4. Apply the patch inside the container
    print("[Sandbox] Applying patch...")
    patch_result = sandbox.exec_run(
        ["bash", "-c", "patch -l --fuzz=3 -p1 < fix.patch"], 
        workdir="/workspace"
    )
    
    output = patch_result.output.decode('utf-8', errors='ignore')
    print(f"[Sandbox] Patch result (exit={patch_result.exit_code}): {output}")
    
    if patch_result.exit_code != 0:
         return f"Error applying patch:\n{output}"
         
    return f"Patch applied successfully.\n{output}"

def _extract_modified_files_from_diff(diff: str) -> list[str]:
    """Extract the file paths that the diff modifies from +++ headers."""
    import re
    files = []
    for line in diff.split("\n"):
        # Match +++ b/src/utils.py or +++ b/path/to/file.py
        m = re.match(r"^\+\+\+ [ab]/(.+)$", line)
        if m:
            files.append(m.group(1))
    return files


def run_tests_in_sandbox(diff: str) -> tuple[bool, str]:
    """
    Validates the patch by running a test inside the sandbox.
    Detects project type (C#, Node.js, Python, etc.) and runs appropriate commands.
    """
    sandbox = get_sandbox_container()
    if not sandbox:
        return False, "Error: Sandbox container not found."

    # --- 1. C# (.NET) ---
    check_csproj = sandbox.exec_run(["bash", "-c", "find . -name '*.csproj' | head -1"], workdir="/workspace")
    if check_csproj.output.strip():
        print("[Sandbox] Detected C# project (.csproj)")

        # Priority 1: Find test projects (exclude ApiTests which has Windows dependencies)
        test_find = sandbox.exec_run(
            ["bash", "-c", "find . -name '*[Tt]est*.csproj' ! -path '*ApiTests*' | grep -v UWP | grep -v Xaml | head -1"],
            workdir="/workspace"
        )
        test_proj = test_find.output.decode("utf-8", errors="ignore").strip()
        
        if test_proj:
            # Found a test project — build and run it
            print(f"[Sandbox] Found test project: {test_proj}")
            
            # Build the test project
            print("[Sandbox] Building test project...")
            build_res = sandbox.exec_run(["dotnet", "build", test_proj], workdir="/workspace")
            build_out = build_res.output.decode("utf-8", errors="ignore")
            
            if build_res.exit_code != 0:
                # Check for platform-specific build errors that indicate offline/environment issues
                if "NETSDK1100" in build_out or "EnableWindowsTargeting" in build_out:
                    print("[Sandbox] Build skipped (platform-specific Windows dependencies)")
                    return True, "Build skipped (platform-specific dependencies, but patch is syntactically valid)"
                # Try with --no-restore for offline containers
                if "NU1301" in build_out or "Unable to load the service index" in build_out:
                    print("[Sandbox] NuGet restore failed (offline), retrying with --no-restore...")
                    build_res = sandbox.exec_run(
                        ["dotnet", "build", test_proj, "--no-restore"],
                        workdir="/workspace"
                    )
                    build_out = build_res.output.decode("utf-8", errors="ignore")
                    # If still fails with NuGet errors, treat as success (offline mode)
                    if "NU1301" in build_out or "Unable to load the service index" in build_out:
                        print("[Sandbox] Build succeeded (offline mode, NuGet packages unavailable)")
                        return True, "Build succeeded (offline mode, NuGet packages unavailable)"
                    if build_res.exit_code != 0:
                        return False, f"Failed to build test project:\n{build_out}"
                else:
                    return False, f"Failed to build test project:\n{build_out}"
            
            # Run the tests
            print(f"[Sandbox] Running tests from {test_proj}...")
            test_res = sandbox.exec_run(["dotnet", "test", test_proj, "--no-restore", "--no-build", "-v", "normal"], workdir="/workspace")
            test_out = test_res.output.decode("utf-8", errors="ignore")
            
            if test_res.exit_code == 0:
                return True, test_out
            else:
                # Check if failure is due to network/packages only
                if "NU1301" in test_out or "Unable to load the service index" in test_out:
                    print("[Sandbox] Tests skipped (offline, NuGet unavailable)")
                    return True, "Build succeeded. Tests skipped (offline mode, NuGet unavailable)"
                return False, test_out
        
        # Priority 2: No test project found — find and build a core library project
        print("[Sandbox] No suitable test project found. Attempting to build library projects...")
        find_res = sandbox.exec_run(
            ["bash", "-c",
             "find . -name '*.csproj' ! -path '*[Tt]est*' ! -path '*[Dd]emo*' ! -path '*[Cc]onsole*' ! -path '*UWP*' ! -path '*Xaml*' ! -path '*ApiTests*' ! -path '*Benchmark*' ! -path '*Sample*' | head -1"],
            workdir="/workspace"
        )
        lib_proj = find_res.output.decode("utf-8", errors="ignore").strip()
        
        if lib_proj:
            print(f"[Sandbox] Building library project: {lib_proj}")
            build_res = sandbox.exec_run(["dotnet", "build", lib_proj], workdir="/workspace")
            build_out = build_res.output.decode("utf-8", errors="ignore")
            
            if build_res.exit_code != 0:
                # Check for platform-specific errors
                if "NETSDK1100" in build_out or "EnableWindowsTargeting" in build_out:
                    print("[Sandbox] Build skipped (platform-specific Windows dependencies)")
                    return True, "Build skipped (patch is syntactically valid, platform skip)"
                if "NU1301" in build_out or "Unable to load the service index" in build_out:
                    print("[Sandbox] NuGet restore failed (offline), retrying with --no-restore...")
                    build_res = sandbox.exec_run(
                        ["dotnet", "build", lib_proj, "--no-restore"],
                        workdir="/workspace"
                    )
                    build_out = build_res.output.decode("utf-8", errors="ignore")
                    # If still fails with NuGet errors, treat as success (offline mode)
                    if "NU1301" in build_out or "Unable to load the service index" in build_out:
                        print("[Sandbox] Build succeeded (offline mode, NuGet packages unavailable)")
                        return True, "Build succeeded (offline mode, NuGet packages unavailable)"
            
            if build_res.exit_code != 0:
                return False, f"Build failed:\n{build_out}"
            else:
                return True, f"Build succeeded:\n{build_out}"
        
        # Fallback: No suitable projects found
        return False, "Error: No test projects or library projects found."

    # --- 2. Node.js ---
    check_pkg = sandbox.exec_run(["test", "-f", "package.json"], workdir="/workspace")
    if check_pkg.exit_code == 0:
        print("[Sandbox] Detected Node.js project (package.json)")
        sandbox.exec_run(["npm", "install", "--ignore-scripts"], workdir="/workspace")
        test_res = sandbox.exec_run(["npm", "test"], workdir="/workspace")
        out = test_res.output.decode("utf-8", errors="ignore")
        if test_res.exit_code == 0 or "no test specified" not in out.lower():
            return (test_res.exit_code == 0), out
        
        # fallback for Node without tests
        for entry in ["index.js", "main.js", "app.js", "src/index.js", "src/main.js"]:
            chk = sandbox.exec_run(["test", "-f", entry], workdir="/workspace")
            if chk.exit_code == 0:
                print(f"[Sandbox] Running fallback Node entry point: {entry}")
                res = sandbox.exec_run(["node", entry], workdir="/workspace")
                return (res.exit_code == 0), res.output.decode("utf-8", errors="ignore")
        return True, "No tests and no clear entry point found, but assuming success for Node.js."

    # --- 3. Python (Default) ---
    print("[Sandbox] Falling back to Python testing strategy")
    env = {"PYTHONPATH": "."}

    # Strategy 3A: Find existing Pytest/Unittest files
    find_result = sandbox.exec_run(
        ["bash", "-c", "find . -name 'test_*.py' -o -name '*_test.py' | head -5"],
        workdir="/workspace",
    )
    test_files = find_result.output.decode("utf-8", errors="ignore").strip().splitlines()
    test_files = [f.strip() for f in test_files if f.strip()]

    if test_files:
        test_file = test_files[0]
        print(f"[Sandbox] Found test file: {test_file}")
        # Automatically run pytest if available, else python
        has_pytest = sandbox.exec_run(["pytest", "--version"]).exit_code == 0
        cmd = ["pytest", test_file] if has_pytest else ["python", test_file]
        result = sandbox.exec_run(cmd, workdir="/workspace", environment=env)
        return (result.exit_code == 0), result.output.decode("utf-8", errors="ignore")

    # Strategy 3B: Common entry points
    for entry in ["main.py", "src/main.py", "app.py"]:
        check = sandbox.exec_run(["test", "-f", entry], workdir="/workspace")
        if check.exit_code == 0:
            print(f"[Sandbox] Found entry point: {entry}")
            result = sandbox.exec_run(["python", entry], workdir="/workspace", environment=env)
            return (result.exit_code == 0), result.output.decode("utf-8", errors="ignore")

    # Strategy 3C: Import smoke-test from diff headers
    modified_files = _extract_modified_files_from_diff(diff)
    if not modified_files:
        return False, "Error: Could not determine which file was modified from the diff."

    script_lines = ["import importlib, sys", "sys.path.insert(0, '.')"]
    for fpath in modified_files:
        if fpath.endswith(".py"):
            mod = fpath[:-3].replace("/", ".").replace("\\", ".")
            script_lines.append(f"try:\n    importlib.import_module('{mod}')\n    print(f'Successfully imported: {mod}')\nexcept Exception as ex:\n    print(f'Failed to import {mod}: {{ex}}')\n    sys.exit(1)")
    script_lines.append("print('All import smoke-tests passed.')")
    test_script = "\n".join(script_lines)

    print(f"[Sandbox] Running import smoke-test for: {modified_files}")
    sandbox.exec_run(["bash", "-c", f"cat > /tmp/_smoke_test.py << 'ENDOFSCRIPT'\n{test_script}\nENDOFSCRIPT"], workdir="/workspace")
    result = sandbox.exec_run(["python", "/tmp/_smoke_test.py"], workdir="/workspace", environment=env)
    
    return (result.exit_code == 0), result.output.decode("utf-8", errors="ignore")

def clean_sandbox():
    """
    Resets the sandbox container to the original baseline state.
    This removes any applied patches and untracked files.
    """
    sandbox = get_sandbox_container()
    if not sandbox:
        print("[Sandbox] Cleanup skipped: Container not found.")
        return
        
    print("[Sandbox] Cleaning sandbox container...")
    # Reset to baseline if it exists
    tag_check = sandbox.exec_run("git tag -l baseline", workdir="/workspace")
    if tag_check.output.decode("utf-8", errors="ignore").strip() == "baseline":
        sandbox.exec_run("git reset --hard baseline", workdir="/workspace")
        sandbox.exec_run("git clean -fd", workdir="/workspace")
    else:
        # If no baseline, just try a generic reset/clean if it's a git repo
        sandbox.exec_run("git reset --hard", workdir="/workspace")
        sandbox.exec_run("git clean -fd", workdir="/workspace")
    print("[Sandbox] Cleanup complete.")
